
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 23;
  public static final int CURLYB_O = 39;
  public static final int NUMBER_RANK = 24;
  public static final int CHAR = 28;
  public static final int ASTERISK = 14;
  public static final int NOMBRE = 2;
  public static final int ENTERO = 31;
  public static final int CURLYB_C = 40;
  public static final int INT = 43;
  public static final int REGEX = 11;
  public static final int LOWER_C = 35;
  public static final int LETTER_RANK = 25;
  public static final int SEMICOLON = 7;
  public static final int COMMA = 34;
  public static final int TAB = 21;
  public static final int SEPARATOR = 9;
  public static final int VERSION = 3;
  public static final int QUESTION_MARK = 13;
  public static final int PLUS = 15;
  public static final int QUOTE = 42;
  public static final int AMPERSAND = 27;
  public static final int ID = 10;
  public static final int VER_RES = 41;
  public static final int EOF = 0;
  public static final int EQUAL = 26;
  public static final int error = 1;
  public static final int JAVAC = 12;
  public static final int CADENA = 33;
  public static final int PIPE = 16;
  public static final int ROUNDB_O = 17;
  public static final int REAL = 32;
  public static final int COLON = 8;
  public static final int ROUNDB_C = 18;
  public static final int NO = 30;
  public static final int UPPER_C = 36;
  public static final int AUTOR = 4;
  public static final int DOUBLE_COLON = 38;
  public static final int NEW_LINE = 22;
  public static final int EXTENSION = 6;
  public static final int SQUAREB_O = 19;
  public static final int TERMINAL = 29;
  public static final int LANZAMIENTO = 5;
  public static final int SQUAREB_C = 20;
  public static final int RESULT = 37;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NOMBRE",
  "VERSION",
  "AUTOR",
  "LANZAMIENTO",
  "EXTENSION",
  "SEMICOLON",
  "COLON",
  "SEPARATOR",
  "ID",
  "REGEX",
  "JAVAC",
  "QUESTION_MARK",
  "ASTERISK",
  "PLUS",
  "PIPE",
  "ROUNDB_O",
  "ROUNDB_C",
  "SQUAREB_O",
  "SQUAREB_C",
  "TAB",
  "NEW_LINE",
  "SPACE",
  "NUMBER_RANK",
  "LETTER_RANK",
  "EQUAL",
  "AMPERSAND",
  "CHAR",
  "TERMINAL",
  "NO",
  "ENTERO",
  "REAL",
  "CADENA",
  "COMMA",
  "LOWER_C",
  "UPPER_C",
  "RESULT",
  "DOUBLE_COLON",
  "CURLYB_O",
  "CURLYB_C",
  "VER_RES",
  "QUOTE",
  "INT"
  };
}

